// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolMessages.proto

package com.lykke.matching.engine.messages;

public final class ProtocolMessages {
  private ProtocolMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CashOperationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lykke.matching.engine.messages.CashOperation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required int64 uid = 1;</code>
     */
    long getUid();

    /**
     * <code>required string accountId = 2;</code>
     */
    boolean hasAccountId();
    /**
     * <code>required string accountId = 2;</code>
     */
    java.lang.String getAccountId();
    /**
     * <code>required string accountId = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccountIdBytes();

    /**
     * <code>required int64 date = 3;</code>
     */
    boolean hasDate();
    /**
     * <code>required int64 date = 3;</code>
     */
    long getDate();

    /**
     * <code>required string assetId = 4;</code>
     */
    boolean hasAssetId();
    /**
     * <code>required string assetId = 4;</code>
     */
    java.lang.String getAssetId();
    /**
     * <code>required string assetId = 4;</code>
     */
    com.google.protobuf.ByteString
        getAssetIdBytes();

    /**
     * <code>required double amount = 5;</code>
     */
    boolean hasAmount();
    /**
     * <code>required double amount = 5;</code>
     */
    double getAmount();
  }
  /**
   * Protobuf type {@code com.lykke.matching.engine.messages.CashOperation}
   */
  public  static final class CashOperation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.lykke.matching.engine.messages.CashOperation)
      CashOperationOrBuilder {
    // Use CashOperation.newBuilder() to construct.
    private CashOperation(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private CashOperation() {
      uid_ = 0L;
      accountId_ = "";
      date_ = 0L;
      assetId_ = "";
      amount_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CashOperation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              accountId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              date_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              assetId_ = bs;
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              amount_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lykke.matching.engine.messages.ProtocolMessages.internal_static_com_lykke_matching_engine_messages_CashOperation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lykke.matching.engine.messages.ProtocolMessages.internal_static_com_lykke_matching_engine_messages_CashOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lykke.matching.engine.messages.ProtocolMessages.CashOperation.class, com.lykke.matching.engine.messages.ProtocolMessages.CashOperation.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>required int64 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    public static final int ACCOUNTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object accountId_;
    /**
     * <code>required string accountId = 2;</code>
     */
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string accountId = 2;</code>
     */
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accountId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string accountId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 3;
    private long date_;
    /**
     * <code>required int64 date = 3;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 date = 3;</code>
     */
    public long getDate() {
      return date_;
    }

    public static final int ASSETID_FIELD_NUMBER = 4;
    private volatile java.lang.Object assetId_;
    /**
     * <code>required string assetId = 4;</code>
     */
    public boolean hasAssetId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string assetId = 4;</code>
     */
    public java.lang.String getAssetId() {
      java.lang.Object ref = assetId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          assetId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string assetId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAssetIdBytes() {
      java.lang.Object ref = assetId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 5;
    private double amount_;
    /**
     * <code>required double amount = 5;</code>
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required double amount = 5;</code>
     */
    public double getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccountId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAssetId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccountIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, date_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAssetIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, amount_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccountIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, date_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAssetIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.lykke.matching.engine.messages.ProtocolMessages.CashOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lykke.matching.engine.messages.ProtocolMessages.CashOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lykke.matching.engine.messages.ProtocolMessages.CashOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lykke.matching.engine.messages.ProtocolMessages.CashOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lykke.matching.engine.messages.ProtocolMessages.CashOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lykke.matching.engine.messages.ProtocolMessages.CashOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lykke.matching.engine.messages.ProtocolMessages.CashOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lykke.matching.engine.messages.ProtocolMessages.CashOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lykke.matching.engine.messages.ProtocolMessages.CashOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lykke.matching.engine.messages.ProtocolMessages.CashOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lykke.matching.engine.messages.ProtocolMessages.CashOperation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lykke.matching.engine.messages.CashOperation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lykke.matching.engine.messages.CashOperation)
        com.lykke.matching.engine.messages.ProtocolMessages.CashOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lykke.matching.engine.messages.ProtocolMessages.internal_static_com_lykke_matching_engine_messages_CashOperation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lykke.matching.engine.messages.ProtocolMessages.internal_static_com_lykke_matching_engine_messages_CashOperation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lykke.matching.engine.messages.ProtocolMessages.CashOperation.class, com.lykke.matching.engine.messages.ProtocolMessages.CashOperation.Builder.class);
      }

      // Construct using com.lykke.matching.engine.messages.ProtocolMessages.CashOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        accountId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        assetId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        amount_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lykke.matching.engine.messages.ProtocolMessages.internal_static_com_lykke_matching_engine_messages_CashOperation_descriptor;
      }

      public com.lykke.matching.engine.messages.ProtocolMessages.CashOperation getDefaultInstanceForType() {
        return com.lykke.matching.engine.messages.ProtocolMessages.CashOperation.getDefaultInstance();
      }

      public com.lykke.matching.engine.messages.ProtocolMessages.CashOperation build() {
        com.lykke.matching.engine.messages.ProtocolMessages.CashOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lykke.matching.engine.messages.ProtocolMessages.CashOperation buildPartial() {
        com.lykke.matching.engine.messages.ProtocolMessages.CashOperation result = new com.lykke.matching.engine.messages.ProtocolMessages.CashOperation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accountId_ = accountId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.assetId_ = assetId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.amount_ = amount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lykke.matching.engine.messages.ProtocolMessages.CashOperation) {
          return mergeFrom((com.lykke.matching.engine.messages.ProtocolMessages.CashOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lykke.matching.engine.messages.ProtocolMessages.CashOperation other) {
        if (other == com.lykke.matching.engine.messages.ProtocolMessages.CashOperation.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasAccountId()) {
          bitField0_ |= 0x00000002;
          accountId_ = other.accountId_;
          onChanged();
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasAssetId()) {
          bitField0_ |= 0x00000008;
          assetId_ = other.assetId_;
          onChanged();
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          return false;
        }
        if (!hasAccountId()) {
          return false;
        }
        if (!hasDate()) {
          return false;
        }
        if (!hasAssetId()) {
          return false;
        }
        if (!hasAmount()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lykke.matching.engine.messages.ProtocolMessages.CashOperation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lykke.matching.engine.messages.ProtocolMessages.CashOperation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long uid_ ;
      /**
       * <code>required int64 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object accountId_ = "";
      /**
       * <code>required string accountId = 2;</code>
       */
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string accountId = 2;</code>
       */
      public java.lang.String getAccountId() {
        java.lang.Object ref = accountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            accountId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string accountId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccountIdBytes() {
        java.lang.Object ref = accountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string accountId = 2;</code>
       */
      public Builder setAccountId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string accountId = 2;</code>
       */
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accountId_ = getDefaultInstance().getAccountId();
        onChanged();
        return this;
      }
      /**
       * <code>required string accountId = 2;</code>
       */
      public Builder setAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accountId_ = value;
        onChanged();
        return this;
      }

      private long date_ ;
      /**
       * <code>required int64 date = 3;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 date = 3;</code>
       */
      public long getDate() {
        return date_;
      }
      /**
       * <code>required int64 date = 3;</code>
       */
      public Builder setDate(long value) {
        bitField0_ |= 0x00000004;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 date = 3;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object assetId_ = "";
      /**
       * <code>required string assetId = 4;</code>
       */
      public boolean hasAssetId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string assetId = 4;</code>
       */
      public java.lang.String getAssetId() {
        java.lang.Object ref = assetId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            assetId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string assetId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAssetIdBytes() {
        java.lang.Object ref = assetId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          assetId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string assetId = 4;</code>
       */
      public Builder setAssetId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        assetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string assetId = 4;</code>
       */
      public Builder clearAssetId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        assetId_ = getDefaultInstance().getAssetId();
        onChanged();
        return this;
      }
      /**
       * <code>required string assetId = 4;</code>
       */
      public Builder setAssetIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        assetId_ = value;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>required double amount = 5;</code>
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required double amount = 5;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>required double amount = 5;</code>
       */
      public Builder setAmount(double value) {
        bitField0_ |= 0x00000010;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double amount = 5;</code>
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        amount_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lykke.matching.engine.messages.CashOperation)
    }

    // @@protoc_insertion_point(class_scope:com.lykke.matching.engine.messages.CashOperation)
    private static final com.lykke.matching.engine.messages.ProtocolMessages.CashOperation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lykke.matching.engine.messages.ProtocolMessages.CashOperation();
    }

    public static com.lykke.matching.engine.messages.ProtocolMessages.CashOperation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<CashOperation> PARSER =
        new com.google.protobuf.AbstractParser<CashOperation>() {
      public CashOperation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new CashOperation(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CashOperation> getParserForType() {
      return PARSER;
    }

    public com.lykke.matching.engine.messages.ProtocolMessages.CashOperation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lykke_matching_engine_messages_CashOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lykke_matching_engine_messages_CashOperation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ProtocolMessages.proto\022\"com.lykke.matc" +
      "hing.engine.messages\"^\n\rCashOperation\022\013\n" +
      "\003uid\030\001 \002(\003\022\021\n\taccountId\030\002 \002(\t\022\014\n\004date\030\003 " +
      "\002(\003\022\017\n\007assetId\030\004 \002(\t\022\016\n\006amount\030\005 \002(\001B6\n\"" +
      "com.lykke.matching.engine.messagesB\020Prot" +
      "ocolMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lykke_matching_engine_messages_CashOperation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lykke_matching_engine_messages_CashOperation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_lykke_matching_engine_messages_CashOperation_descriptor,
        new java.lang.String[] { "Uid", "AccountId", "Date", "AssetId", "Amount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
