version: "2"
services:
  me:
    image: lykkex/matchingengine
    environment:
        - HTTP_CONFIG=ME_HTTP_CONFIG
        - JAVA_OPTS=-ME_JAVA_OPTS
    ports:
      - "8886:8886"
      - "8887:8887"
      - "8888:8888"
      - "8889:8889"
    volumes:
          - LOGS_DIR:/lykke-me-prototype/log
          - ORDERS_DIR:/lykke-me-prototype/orders