package com.lykke.matching.engine.logging

val ME_STATUS = "MeStatus"
val ME_CONNECTIONS_DETAILS = "MeConnectionsDetails"
val ME_CONNECTIONS_COUNT = "MeConnectionsCount"
val ME_CONNECTIONS_INCOMING = "MeConnectionsIncoming"
val ME_CONNECTIONS_OUTGOING = "MeConnectionsOutgoing"
val ME_BALANCE_UPDATE = "MeBalanceUpdate"
val ME_CASH_OPERATION = "MeCashOperation"
val ME_LIMIT_ORDER_CANCEL = "MeLimitOrderCancel"
val ME_LIMIT_ORDER = "MeLimitOrder"
val ME_MARKET_ORDER = "MeMarketOrder"
val ME_BACKEND_QUEUE = "MeBackendQueue"
val ME_ERRORS = "MeErrors"
val ME_RESERVED_BALANCE_UPDATE = "MeReservedBalanceUpdate"
val ME_RESERVED_CASH_OPERATION = "MeReservedCashOperation"

val UID = "Uid"
val ID = "Id"
val BUSSINES_ID = "BussinesId"
val TIMESTAMP = "Timestamp"
val IP = "Ip"
val STATUS = "Status"
val NOTE = "Note"
val CLIENT_ID = "ClientId"
val ASSET = "Asset"
val ASSET_PAIR = "AssetPair"
val AMOUNT = "Amount"
val RESERVED_AMOUNT = "ReservedAmount"
val STRAIGHT = "Straight"
val PRICE = "Price"
val SEND_TO_BITCOIN = "SendToBitcoin"
val LIMIT_ORDER_ID = "LimitOrderId"
val TYPE = "Type"
val DATA = "Data"

val SERVICE = "Service"
val STACK_TRACE = "StackTrace"
